// Generated by https://quicktype.io

export interface MiniCountry {
    name:       Name;
    flags:      Flags;
    population: number;
    region:     Region;
    capital:    string[] | string;
}

export interface Flags {
    png: string;
    svg: string;
}

interface Name {
    common:      string;
    official:    string;
    nativeName?: { [key: string]: NativeName };
}

export interface NativeName {
    official: string;
    common:   string;
}

enum Region {
    Africa = "Africa",
    Americas = "Americas",
    Antarctic = "Antarctic",
    Asia = "Asia",
    Europe = "Europe",
    Oceania = "Oceania",
}
